---

version: "2"

volumes:
  mysqlData:
    driver: local

services:
  webserver:
    image: "nginx:1.11"
    links: ["php"]
    volumes:
      - "./Build/docker/nginx.conf:/etc/nginx/nginx.conf"
      - "./:/var/www/"
      - "./logs/webserver/:/var/log/nginx/"
    env_file:
      - "./.env"
    environment:
      VIRTUAL_HOST: "${HOSTNAME}"
      VIRTUAL_PORT: 80
  php:
    # https://github.com/SimplyAdmire/docker
    image: "simplyadmire/php"
    command: "php-fpm7.0 -F"
    volumes:
      - "./Build/docker/php-fpm-pool.conf:/etc/php/7.0/fpm/pool.d/www.conf"
      - "./Build/docker/ssmtp.conf:/etc/ssmtp/ssmtp.conf"
      - "./Build/docker/mailcatcher.ini:/etc/php/7.0/cli/conf.d/mailcatcher.ini"
      - "./:/var/www/"
    working_dir: "/var/www/"
    env_file:
      - "./.env"
    links:
      - "db"
      - "elastic"
  mailcatcher:
    image: "schickling/mailcatcher"
    environment:
      VIRTUAL_HOST: "mailcatcher.${HOSTNAME}"
      VIRTUAL_PORT: 1080
  db:
    image: "mariadb"
    env_file:
      - "./.env"
    volumes:
      - "mysqlData:/var/lib/mysql"
      - "./../logs/db/:/var/log/mysql/"
      - "./Build/docker/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf"
  npm:
    image: "simplyadmire/npm:latest"
    working_dir: "/app/src/SimplyAdmire.MyPackage/Build/"
    entrypoint: "yarn"
    volumes:
      - "./Build/docker/run-npm.sh:/root/run-npm.sh"
      - "./:/app/"
      - "~/.gitconfig:/root/.gitconfig"
  composer:
    image: "composer/composer:latest"
    working_dir: "/app/"
    volumes:
      - "./:/app/"
      - "~/.composer/:/composer/"
    env_file:
      - "./.env"
  elastic:
    image: "elasticsearch:1.7"
    command: elasticsearch -Des.network.host=0.0.0.0
    environment:
      VIRTUAL_HOST: "elastic.${HOSTNAME}"
      VIRTUAL_PORT: 9200
    volumes:
      - "./Build/docker/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml"
  redis:
    image: "redis"
